# This workflow will build a docker container, publish it to Google Container Registry, and deploy it to GKE when a release is created
#
# To configure this workflow:
#
# 1. Ensure that your repository contains the necessary configuration for your Google Kubernetes Engine cluster, including deployment.yml, kustomization.yml, service.yml, etc.
#
# 2. Set up secrets in your workspace: GKE_PROJECT with the name of the project and GKE_SA_KEY with the Base64 encoded JSON service account key (https://github.com/GoogleCloudPlatform/github-actions/tree/docs/service-account-key/setup-gcloud#inputs).
#
# 3. Change the values for the GKE_ZONE, GKE_CLUSTER, IMAGE, and DEPLOYMENT_NAME environment variables (below).
#
# For more support on how to run the workflow, please visit https://github.com/google-github-actions/setup-gcloud/tree/master/example-workflows/gke

name: Build image and run on Kubeflow

on:
  push:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  IAP_CLIENT_ID: ${{ secrets.IAP_CLIENT_ID }}
  IMAGE: kedro-kubeflow-demo

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}
        export_default_credentials: true

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker

    # Build the Docker image
    - name: Build
      run: |-
        pip3 install kedro-docker
        docker pull "gcr.io/$PROJECT_ID/$IMAGE:latest" || true        
        /home/runner/.local/bin/kedro docker build --image "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" --docker-args "--cache-from gcr.io/$PROJECT_ID/$IMAGE:latest" --gid 0

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        docker push "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"
        docker tag "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" "gcr.io/$PROJECT_ID/$IMAGE:latest"
        docker push "gcr.io/$PROJECT_ID/$IMAGE:latest"

    - name: Deploy pipeline
      run: |-
        pip3 install git+https://github.com/getindata/kedro-kubeflow.git@allow_effective_user_change
        /home/runner/.local/bin/kedro install
        sed -i -e"s/__GITHUB_SHA__/$GITHUB_SHA/" conf/base/kubeflow.yaml
        /home/runner/.local/bin/kedro kubeflow list-pipelines
        /home/runner/.local/bin/kedro kubeflow run-once
